version: '3'

services:
    api-server:
        build: ./config/api-server
        depends_on:
            - api
        ports:
            - "3000:80"
    api:
        build: ./
        depends_on:
            - db
            - mail-dev
        environment:
            - APP_ENV=${APP_ENV}
            - DB_HOST=${DB_HOST}
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - MAILER_HOST=${MAILER_HOST}
            - MAILER_PORT=${MAILER_PORT}
            - MAILER_USER=${MAILER_USER}
            - MAILER_PASSWORD=${MAILER_PASSWORD}
    db:
        image: postgres:13-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_HOST_AUTH_METHOD=trust
    mail-dev:
        image: djfarrelly/maildev
        ports:
            - "9099:80"
        environment:
            VIRTUAL_HOST: 'maildev.docker'
            VIRTUAL_PORT: 80
        entrypoint: "bin/maildev"
        command:
            - "--web"
            - "80"
            - "--smtp"
            - "25"
            - "--outgoing-host"
            - "$OUTGOINT_HOST"
            - "--outgoing-port"
            - "$OUTGOING_PORT"
            - "--outgoing-user"
            - "$OUTGOING_USER"
            - "--outgoing-pass"
            - "$OUTGOING_PASS"
            - "--outgoing-secure"
